/** Keep startup guidance within clients' initialization-text budgets. */
export const SERVER_INSTRUCTIONS_BUDGET = 1800;
export const SERVER_INSTRUCTIONS = `Before designing or changing infrastructure, call get_context; omit arguments to detect Git. Empty folders work. It returns required rules, guidelines, and module summaries. If selection_required, select relevant available_rulesets from the user's intent and call get_rules with enterprise_id and ruleset_ids (or []) to read their content. Keep setup.enterprise_id and setup.ruleset_ids for later. Existing workspace rules stay authoritative; suggest changes rather than silently attaching them. Resolve selection_required with get_rules; other can_generate: false or access errors still block.

Suggest fitting modules by name and source. Fetch versions with list_modules(module_id), then inspect the chosen version's interface through Terraform tools or authenticated VCS. Never invent inputs or versions. If inspection is blocked, explain and ask before substituting raw resources. Prefer registry_source with version, otherwise source_url with Git ref. With no matching module, draft from scratch under the selected rules.

Draft locally without requiring Git, a remote, or a workspace. When a remote and pushed branch exist during an authorized publish/compliance flow, call setup_workspace with the saved setup selection. It reuses or creates the repository workspace and configures delivery hooks. Don't ask for already-known choices or create a remote/push/deploy without authorization. Preserve IDs on partial failure; never blindly recreate a workspace. Recheck code against returned current rules.

Compliance evaluates pushed code. Check once for a run covering the pushed commit; if none, trigger with the branch ref, including when the push preceded webhook setup. Share its URL without polling. Surface webhook/setup failures; never equate drafting with passing compliance.`;
